import { StemMathDefinitionSchema } from '@gosp/contracts';

export function createSolarDeploymentStemMathDefinition() {
  return StemMathDefinitionSchema.parse({
    quantities: [
      { id: 'solar.rated-power', label: 'Controlled rated power', symbol: 'Prated', unit: 'W', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.parameters.fixedPanel.ratedPowerW' },
      { id: 'solar.irradiance', label: 'Controlled irradiance', symbol: 'irradiance', unit: 'W/m2', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.environment.irradianceWm2' },
      { id: 'solar.incidence-angle', label: 'Controlled incidence angle', symbol: 'angle', unit: 'deg', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.environment.incidenceAngleDeg' },
      { id: 'solar.temperature-factor', label: 'Calculated temperature factor', symbol: 'temperatureFactor', role: 'intermediate', status: 'calculated', source: 'intermediate-value', sourcePath: 'solar-temperature-factor' },
      { id: 'solar.soiling-loss', label: 'Controlled soiling loss', symbol: 'soilingLoss', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.parameters.soilingLossFraction' },
      { id: 'solar.deployed-fraction', label: 'Deployed panel fraction', symbol: 'deployedFraction', role: 'input', status: 'submitted', source: 'material-input', sourcePath: 'submission.materialPayload.deployment.deployedFraction' },
      { id: 'solar.instantaneous-power', label: 'Modeled instantaneous power', symbol: 'P', unit: 'W', role: 'output', status: 'calculated', source: 'evaluation-result', sourcePath: 'result.power.instantaneousPowerW', resultPath: 'evaluation.result.power.instantaneousPowerW' },
      { id: 'solar.core-radius', label: 'Roll-core radius', symbol: 'coreRadius', unit: 'm', role: 'input', status: 'submitted', source: 'material-input', sourcePath: 'submission.materialPayload.deployment.coreRadiusM' },
      { id: 'solar.minimum-bend-radius', label: 'Controlled minimum bend radius', symbol: 'minimumBendRadius', unit: 'm', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.parameters.fixedPanel.minimumBendRadiusM' },
      { id: 'solar.bend-margin', label: 'Modeled bend-radius margin', symbol: 'bendRadiusMargin', unit: 'm', role: 'output', status: 'calculated', source: 'evaluation-result', sourcePath: 'result.deployment.bendRadiusMarginM', resultPath: 'evaluation.result.deployment.bendRadiusMarginM' },
      { id: 'solar.hazard-wind', label: 'Controlled hazard threshold', symbol: 'hazardWind', unit: 'm/s', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.operatingConditions.hazardWindThresholdMps' },
      { id: 'solar.current-wind', label: 'Controlled current wind', symbol: 'currentWind', unit: 'm/s', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.environment.windSpeedMps' },
      { id: 'solar.trigger-wind', label: 'Stow trigger wind', symbol: 'triggerWind', unit: 'm/s', role: 'input', status: 'submitted', source: 'material-input', sourcePath: 'submission.materialPayload.control.windStowTriggerMps' },
      { id: 'solar.wind-rise-rate', label: 'Controlled modeled wind-rise rate', symbol: 'windRiseRate', unit: 'm/s2', role: 'controlled', status: 'controlled', source: 'material-input', sourcePath: 'compiledScenario.environment.modeledWindRiseRateMpsPerSecond' },
      { id: 'solar.sensor-latency', label: 'Sensor latency', symbol: 'sensorLatency', unit: 's', role: 'input', status: 'submitted', source: 'material-input', sourcePath: 'submission.materialPayload.control.sensorLatencySeconds' },
      { id: 'solar.controller-latency', label: 'Controller latency', symbol: 'controllerLatency', unit: 's', role: 'input', status: 'submitted', source: 'material-input', sourcePath: 'submission.materialPayload.control.controllerLatencySeconds' },
      { id: 'solar.stow-time', label: 'Stow duration', symbol: 'stowTime', unit: 's', role: 'input', status: 'submitted', source: 'material-input', sourcePath: 'submission.materialPayload.deployment.stowTimeSeconds' },
      { id: 'solar.available-stow-time', label: 'Modeled available stow time', symbol: 'availableTime', unit: 's', role: 'intermediate', status: 'calculated', source: 'intermediate-value', sourcePath: 'solar-available-stow-time' },
      { id: 'solar.required-response-time', label: 'Modeled required response time', symbol: 'requiredTime', unit: 's', role: 'intermediate', status: 'calculated', source: 'intermediate-value', sourcePath: 'solar-required-response-time' },
      { id: 'solar.stow-margin', label: 'Modeled storm-stow margin', symbol: 'stowTimeMargin', unit: 's', role: 'output', status: 'calculated', source: 'evaluation-result', sourcePath: 'result.storm.stowTimeMarginSeconds', resultPath: 'evaluation.result.storm.stowTimeMarginSeconds' },
    ],
    equations: [
      { equationId: 'solar.power', variableBindings: { Prated: 'solar.rated-power', irradiance: 'solar.irradiance', angle: 'solar.incidence-angle', temperatureFactor: 'solar.temperature-factor', soilingLoss: 'solar.soiling-loss', deployedFraction: 'solar.deployed-fraction' }, intermediateQuantityIds: ['solar.temperature-factor'], outputQuantityId: 'solar.instantaneous-power', dimensionalStatus: 'not-checked', assumptions: ['Irradiance, temperature, incidence, and soiling remain constant for the instantaneous screen.'], limitations: ['This is not an electrical system, energy-yield, shading, or manufacturer-performance model.'] },
      { equationId: 'solar.bend-margin', variableBindings: { coreRadius: 'solar.core-radius', minimumBendRadius: 'solar.minimum-bend-radius' }, intermediateQuantityIds: [], outputQuantityId: 'solar.bend-margin', dimensionalStatus: 'checked', assumptions: [], limitations: ['A positive radius margin does not establish fatigue, laminate, wiring, or structural safety.'] },
      { equationId: 'solar.stow-margin', variableBindings: { hazardWind: 'solar.hazard-wind', currentWind: 'solar.current-wind', triggerWind: 'solar.trigger-wind', windRiseRate: 'solar.wind-rise-rate', sensorLatency: 'solar.sensor-latency', controllerLatency: 'solar.controller-latency', stowTime: 'solar.stow-time' }, intermediateQuantityIds: ['solar.available-stow-time', 'solar.required-response-time'], outputQuantityId: 'solar.stow-margin', dimensionalStatus: 'checked', assumptions: ['Wind speed rises linearly at the controlled synthetic rate.'], limitations: ['This timing screen is not a weather forecast, wind-load analysis, controls validation, or safety case.'] },
    ],
  });
}
