import { StemScienceDefinitionSchema } from '@gosp/contracts';

export function createCleanWaterStemScienceDefinition() {
  return StemScienceDefinitionSchema.parse({
    treatment: 'physical-domain',
    items: [
      {
        id: 'clean-water.science.volume-balance',
        title: 'Volume-balance constraint',
        classification: 'principle',
        statement: 'A bounded flow calculation should not produce more tracked output volume than the available source or modeled pump capacity permits.',
        applicability: {
          status: 'applicable',
          description: 'Applied as a conceptual constraint in the level-1 screening relationship.',
        },
        limitations: ['No authoritative science source is attached in this local educational fixture.'],
        sourceStatus: 'unavailable',
        evidenceStatus: 'model-only',
        sourceRefs: [],
        evidenceRefs: [],
        equationIds: ['clean-water.flow-screen'],
        quantityIds: ['clean-water.source-liters', 'clean-water.pump-capacity', 'clean-water.clean-water-liters'],
      },
      {
        id: 'clean-water.science.flow-screen-equation',
        title: 'Level-1 flow-screen equation',
        classification: 'model-equation',
        statement: 'The recorded model limits pre-efficiency volume by source availability and pump capacity, then applies the declared efficiency input.',
        applicability: {
          status: 'applicable',
          description: 'Applicable only to the recorded educational screening model and controlled scenario.',
        },
        limitations: ['The equation omits transient behavior, pressure, head loss, leakage, storage dynamics, and water-quality mechanisms.'],
        sourceStatus: 'model-declared',
        evidenceStatus: 'model-only',
        sourceRefs: [],
        evidenceRefs: [],
        equationIds: ['clean-water.flow-screen'],
        quantityIds: ['clean-water.source-liters', 'clean-water.pump-flow', 'clean-water.duration', 'clean-water.filter-efficiency', 'clean-water.clean-water-liters'],
      },
      {
        id: 'clean-water.science.constant-operation-approximation',
        title: 'Constant-operation approximation',
        classification: 'engineering-approximation',
        statement: 'Pump flow and filter efficiency are treated as constant over the modeled duration.',
        applicability: {
          status: 'unknown',
          description: 'Adequacy for a physical device has not been established.',
        },
        limitations: ['Real pump and filter behavior may vary with time, loading, voltage, pressure, and media condition.'],
        sourceStatus: 'model-declared',
        evidenceStatus: 'model-only',
        sourceRefs: [],
        evidenceRefs: [],
        equationIds: ['clean-water.flow-screen'],
        quantityIds: ['clean-water.pump-flow', 'clean-water.duration', 'clean-water.filter-efficiency'],
      },
      {
        id: 'clean-water.science.efficiency-relationship',
        title: 'Filter-efficiency relationship',
        classification: 'empirical-relationship',
        statement: 'A physical efficiency relationship would require measured or sourced performance data; this fixture supplies only a synthetic input value.',
        applicability: {
          status: 'unknown',
          description: 'No empirical applicability is established for the synthetic efficiency value.',
        },
        limitations: ['No calibration curve, test method, contaminant definition, or measured dataset is declared.'],
        sourceStatus: 'unavailable',
        evidenceStatus: 'unavailable',
        sourceRefs: [],
        evidenceRefs: [],
        equationIds: ['clean-water.flow-screen'],
        quantityIds: ['clean-water.filter-efficiency'],
      },
      {
        id: 'clean-water.science.efficiency-assumption',
        title: 'Synthetic efficiency assumption',
        classification: 'assumption',
        statement: 'The filter-efficiency value is accepted as a dimensionless educational model input for this run.',
        applicability: {
          status: 'applicable',
          description: 'Applicable to the recorded calculation, not established for a physical filter.',
        },
        limitations: ['The assumed value is not a measured treatment-efficiency claim.'],
        sourceStatus: 'assumption-declared',
        evidenceStatus: 'assumption-only',
        sourceRefs: [],
        evidenceRefs: [],
        equationIds: ['clean-water.flow-screen'],
        quantityIds: ['clean-water.filter-efficiency'],
      },
      {
        id: 'clean-water.science.physical-observation',
        title: 'Physical observation',
        classification: 'observation',
        statement: 'No physical flow or water-quality observation is declared for this local demonstrator.',
        applicability: {
          status: 'not-declared',
          description: 'Observation comparison is deferred to the experiment work package.',
        },
        limitations: ['Calculated values must not be described as measured observations.'],
        sourceStatus: 'not-declared',
        evidenceStatus: 'not-declared',
        sourceRefs: [],
        evidenceRefs: [],
        equationIds: [],
        quantityIds: ['clean-water.clean-water-liters'],
      },
    ],
    disclosures: [
      'Declaring a principle or relationship does not prove that the model represents it adequately.',
      'The recorded Clean Water result is calculated from synthetic inputs; it is not a physical observation, treatment-efficacy result, or potable-water validation.',
    ],
  });
}
