import { describe, expect, it } from 'vitest';
import { CostEstimateSchema, ModulePackageSchema, ProblemDefinitionSchema, ProductBindingSchema, ProjectManifestV2Schema, ScoringProfileSchema, SimulationRunEnvelopeSchema, validateModeRequirements } from './index.js';
const confidence={level:'medium' as const,rationale:'foundation fixture'};
const attribution={creators:[{name:'GOSP Forge'}],sourceRefs:[]};
const license={id:'CC-BY-4.0' as const,shareAlike:false};
describe('foundation contracts',()=>{
 it('requires problem metrics and scoring baselines',()=>{expect(ProblemDefinitionSchema.safeParse({kind:'ProblemDefinition',id:'p',version:'1',title:'P',summary:'S',metrics:[]}).success).toBe(false); expect(ProblemDefinitionSchema.safeParse({kind:'ProblemDefinition',id:'p',version:'1',title:'P',summary:'S',mode:'scoring',metrics:[{id:'m',name:'M',unit:'L',direction:'maximize'}]}).success).toBe(false);});
 it('allows incomplete dream projects but blocks scoring projects without problems',()=>{expect(ProjectManifestV2Schema.safeParse({kind:'ProjectManifestV2',manifestVersion:'2',id:'proj',version:'1',title:'Dream',mode:'dream',design:{title:'D',status:'incomplete'}}).success).toBe(true); expect(ProjectManifestV2Schema.safeParse({kind:'ProjectManifestV2',manifestVersion:'2',id:'proj',version:'1',title:'Score',mode:'scoring',design:{title:'D',status:'draft'}}).success).toBe(false);});
 it('validates logical modules without 3D and blocks physical modules without safety',()=>{expect(ModulePackageSchema.safeParse({kind:'ModulePackage',id:'logic',version:'1',name:'Logic',type:'logical',attribution,license,capabilities:{capabilities:['control']},validationStatus:'draft'}).success).toBe(true); expect(ModulePackageSchema.safeParse({kind:'ModulePackage',id:'pump',version:'1',name:'Pump',type:'physical',attribution,license,capabilities:{capabilities:['flow']},validationStatus:'draft'}).success).toBe(false);});
 it('requires sponsor disclosure and spec meaning',()=>{const spec={id:'flow-rate',name:'Flow rate',value:2,unit:'L/min',meaning:{affects:['simulation'],explanation:'Maps to output flow.',targetField:'flowRateLpm'},simulationUse:'Water flow cap'}; expect(ProductBindingSchema.safeParse({kind:'ProductBinding',id:'prod',version:'1',name:'Pump',moduleIds:['pump'],specs:[spec],provenance:{status:'community-submitted',sourceRefs:[]},sponsored:true,confidence}).success).toBe(false);});
 it('requires run envelope proof fields',()=>{expect(SimulationRunEnvelopeSchema.safeParse({kind:'SimulationRunEnvelope',runId:'r',projectId:'p',moduleIds:['m'],inputHash:'a'.repeat(64),outputHash:'b'.repeat(64),modelVersion:'0',fidelityLevel:'level-1-screening',assumptions:[{id:'a',description:'A'}],units:{flow:'L/min'},confidence,limitations:[{id:'l',description:'No potable water claim.'}]}).success).toBe(true);});
 it('blocks sponsor scoring influence and missing estimate confidence',()=>{expect(ScoringProfileSchema.safeParse({id:'s',version:'1',sponsorNeutral:true,components:[{id:'sponsor-boost',label:'Sponsor',weight:1,formula:'1'}]}).success).toBe(false); expect(CostEstimateSchema.safeParse({id:'e',projectId:'p',lines:[],lifecycle:{},contingency:0,total:0,assumptions:['A']}).success).toBe(false);});
 it('applies mode requirements',()=>{expect(validateModeRequirements('dream',{}).some(i=>i.severity==='warning')).toBe(true); expect(validateModeRequirements('scoring',{}).some(i=>i.severity==='blocker')).toBe(true);});
});
